languageCode = "en-us"
title = "R Curriculum"
theme = "hugo_theme_robust"
preserveTaxonomyNames = true
paginate = 100
canonifyurls = true
[[menu.main]]
  name = "Home: R Training Curriculum"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Course Specific Material"
  url = "/course-specific-material/"
  weight = 2
[[menu.main]]
  name = "Introduction to R Course"
  url = "/intro-curriculum/"
  weight = 3
[[menu.main]]
  name = "Introduction to USGS R Packages"
  url = "/usgs-packages/"
  weight = 4
[[menu.main]]
  name = "R Package Development"
  url = "/r-package-dev/"
  weight = 5
