languageCode = "en-us"
title = "Introduction to R"
theme = "hugo_theme_robust"
preserveTaxonomyNames = true
paginate = 100
canonifyurls = true
[[menu.main]]
name = "Home"
identifier = "post"
url = "/"
