languageCode = "en-us"
title = "Introduction to R"
theme = "hugo_theme_robust"
preserveTaxonomyNames = true
paginate = 100
canonifyurls = true
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -1
[[menu.main]]
  name = "Introduction to R Course"
  url = "/intro-curriculum/"
  weight = 1
[[menu.main]]
  name = "Course Specific Material"
  url = "/course-specific-material/"
  weight = 1
